AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'test/**/*'
    - 'db/**/*'
    - 'app/channels/**/*'

Metrics/BlockLength:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 7
Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/GuardClause:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Style/Documentation:
  Enabled: false
